server:
  port: 8082

spring:
  application:
    name: account-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/banking_account
    username: ${DB_USERNAME:banking}
    password: ${DB_PASSWORD:banking}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

banking:
  jwt:
    secret: ${JWT_SECRET:change-me-use-32-char-minimum-secret-key-for-hs256-banking}
    issuer: ${JWT_ISSUER:banking-system}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.banking.account: DEBUG
